### ISSUE TITLE
Add a method to automatically add documents in batches

### ISSUE THREAD

**Issue by bidoubiwa** [meilisearch/integration-guides#106] opened 2021-03-21 13:42 UTC
## Current State

As of now, we have the following methods to add documents:
- `addDocuments`
- `updateDocuments`
Both implicitly create and index and adds documents to the index in one batch. This function works really well in what is expected from it.

## Problem

On big datasets how more documents are added at the same time, how longer the indexing time and how more the RAM has to support heavy force load and could cause a crash.

> MeiliSearch uses a lot of RAM when indexing documents. Be aware of your RAM availability as you increase the size of your batch as this could cause MeiliSearch to crash.

## Solution

To avoid asking our users to chunk their dataset them into smaller batches and then manually call `addDocument` on every batch, we should provide a function that helps out.

The function main idea would be to chunk and upload documents. This will be done by giving a dataset as parameter, and a  a batch size (but there would be a size by default).

## Implementation

We will need a function that slices and avoid iterating on the whole dataset. Every slice should be pushed to MeiliSearch.

Slice function example:
<details>

```javascript
// (one liner that could win in explanation)
const chunck = (arr, size) =>
  Array.from({length: Math.ceil(arr.length / size)}, (val, i) => // only itterates on number of final batches
    arr.slice(i * size, i * size + size)
  )

const input = [1,2,3,4,5,6,7,8];
console.log(chunck(input, 2)); // [ [ 1, 2 ], [ 3, 4 ], [ 5, 6 ], [ 7, 8 ] ]
console.log(chunck(input, 1000)) // [1,2,3,4,5,6,7,8]
```
</details>

### Javascript implementation

```javascript
// Temporary ugly name
const client = new MeiliSearch(config)
const uid = 'small_numbers'

async function addDocumentsInBatches(dataset, { batchSize = 1000 }) {
   // Example : 
   // dataset = 30 documents
   // batchSize = 15

  const numberOfBatches = Math.ceil(dataset.length / batchSize)
    const batchPromises = Array.from({length: numberOfBatches}, (val, i) => {// only itterates length/batchSize times => 2
      const batch = dataset.slice(i * batchSize, i * batchSize + batchSize) // [15 docs]
      return client.index(uid).addDocuments(batch)
    })
   return await Promise.all(batchPromises) // [ { updateId: 1 }, { updateId: 2 } ]
}

```

### Algolia:

[Algolia](https://www.algolia.com/doc/guides/sending-and-managing-data/send-and-update-your-data/how-to/sending-records-in-batches/#using-the-api) does not have a method in a SDK that batches a dataset and push it to algolia.

> To push records in batches, you need to chunk your records, then loop over each chunk and send it to Algolia with the addObjects method.

But they have a `algolia-cli` that provides that possibility using [`import` option](https://github.com/algolia/algolia-cli#5-import--import):

```bash
# see -b (batchSize) option
algolia import -s <sourceFilepath> -a <algoliaAppId> -k <algoliaApiKey> -n <algoliaIndexName> -b <batchSize> -t <transformationFilepath> -m <maxConcurrency> -p <csvToJsonParams>
```

### Elastic:

Elastic gives an example of how to read a dataset file `doc` by `doc` using a stream (avoiding having to import a whole dataset in RAM which can cause an overflow in ram)
[client.helpers.bulk](https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/7.x/client-helpers.html). 

And also provided an option `flushBytes` that acts as, if I understand correctly, a "batch addition".

> the size of the bulk body in bytes to reach before to send it. Default of 5MB.
Default: 5000000

```javascript
const b = client.helpers.bulk({
    datasource: createReadStream('./dataset.ndjson').pipe(split())
   flushBytes: 1000000
})
```

## Questions

We can have two different approaches (at least of what I think of now)

## 1. Add batching in `addDocuments` by adding a parameters  🎉

```js
index.addDocuments({ batchAddition: 1000 }) // (default to none)
```

Cons: 
Maybe to magical ? Hard to create good parameters. `batchAddition: none` is maybe not clear.

Pro:
No new function

## 2. Create new function  ❤️

 "addDocumentsInBatch" (temp name)

```js
index.addDocumentsInBatch({ batchSize: 1000, interval: 500 })  //parameters example
```

Pro: 
Clarity in usage

Cons: 
New function and hard to read function name

If we go with option 2 we should decide on naming
- addBatchedDocuments()
- addDocumentsInBatch()
- other suggestions

-----------------

TODO:
- [x] meilisearch-dart
- [x] meilisearch-dotnet
- [x] meilisearch-go
- [x] meilisearch-java
- [x] meilisearch-js
- [x] meilisearch-php
- [x] meilisearch-python
- [x] meilisearch-ruby
- [x] meilisearch-rust
- [ ] meilisearch-swift

**Comment by curquiza** [comment] 2021-03-22 18:36
I like the second one with `addDocumentsInBatch`.

**Comment by bidoubiwa** [comment] 2021-04-26 13:32
@curquiza  @alallema  the issue is waiting for a vote!

**Comment by alallema** [comment] 2021-04-26 13:40
I vote for:
- Create a new function
- AddDocumentsInBatch()

**Comment by bidoubiwa** [comment] 2021-04-26 17:16
I will create an example before making it ready for implementation

**Comment by curquiza** [comment] 2021-04-26 17:36
Not a priority for the moment, the issue is ready for implementation since the vote is done and seems ok 🙂 (it's not the same context as a template to add, for example, that indeed needs a PR as approval). But we will start the implementation of the first PR once we will decide to take the time to implement it, which is not the case for the moment.

**Comment by sanders41** [comment] 2021-05-18 01:47
I have a way to do this in Python that I am happy to submit as a PR, however I know this isn't a priority so I will wait until if/when you say you all are ready before submitting it.

**Comment by curquiza** [comment] 2021-05-21 13:39
Hello @sanders41,

Sorry I forgot to tell this issue is ready to be implemented and solution 2 was chosen! :)

Feel free to submit a PR, this is really nice of you 😁

**Comment by brunoocasali** [comment] 2023-03-13 19:22
I'm closing this since all the critical SDKs have the feature, and only Swift will be left (and there is an issue open in the repo)!

**Closed by brunoocasali** 2023-03-13 19:22 UTC
Labels: ready to implement, SDKs, issues available in repos
