### ISSUE TITLE
New filter example in SDK README.md for v0.21

### ISSUE THREAD

**Issue by bidoubiwa** [meilisearch/integration-guides#136] opened 2021-07-19 15:56 UTC
# Filter sample in README

Currently in `v0.20` most SDK made an example of filters in their readme.md.

For example in JS (same for PHP, ruby, go, not rust, not java, don't, dart, python, not swift)
```js
await index.search(
  'wonder',
  {
    attributesToHighlight: ['*'],
    filter: 'id > 1' // or based on the books dataset
  }
)
```

We should think about updating them either to something more relevant either by removing them.

## Removing the example 🎉 (vote)

We remove the example completely from the README.md 

## Update the example 👍 (vote)

We could go with a better example by joining this PR: #135 with a new filter example.

The previous example could be changed by the following. Knowing that if we go for `genres=Action` we do not need to change anything in #135.

### String option 👍  :heart:  (vote both)

```js
await index.search(
  'wonder',
  {
    attributesToHighlight: ['*'],
    filter: 'id > 1 AND genres=Action' // or based on the books dataset
  }
)
```

OR

### Array option 👍 👀 (vote both)

```js
await index.search(
  'wonder',
  {
    attributesToHighlight: ['*'],
    filter: ['id > 1', 'genres=Action'] // or based on the books dataset
  }
)
```

## TODO

- [x] meilisearch-dart
- [ ] meilisearch-dotnet
- [x] meilisearch-go
- [ ] meilisearch-java
- [x] meilisearch-js
- [x] meilisearch-php
- [x] meilisearch-python
- [x] meilisearch-ruby
- [x] meilisearch-rust
- [ ] meilisearch-swift

**Comment by alallema** [comment] 2021-07-19 16:17
I think we need to add the line:
```js
client.index('movies')
    .updateAttributesForFaceting([
      'id',
      'genres'
    ])
```
or a link to the documentation but this may make it too much complex for a README.
Did we have a fourth option to remove the `filter` in the first example and add a second example like:
**Simple search**
```js
await index.search(
  'wonder',
  {
    attributesToHighlight: ['*'],
  }
)
```
**Search with filter**
```js
await index.updateAttributesForFaceting([
    'id',
    'genres'
  ])
await index.search(
  'wonder',
  {
    attributesToHighlight: ['*'],
    filters: 'id > 1 AND genres=Action'
  }
)
```

**Comment by curquiza** [comment] 2021-08-24 20:44
I agree with Amélie, it would be worth adding a third example. I don't really like the idea to add the step of "set your `filterable` attributes" in the only one example of a custom search.

So maybe 3 examples?
- basic search: only uses `q`
- custom search: uses `attributesToHighlight`
- custom search with filter: updates `filterableAttributes` + uses `filter`

WDYT?

(sorry for the delay)

**Comment by bidoubiwa** [comment] 2021-10-07 08:32
So we would have: 

### Basic 
```js
await index.search('wonder')
```

### Custom Search
```js
await index.search(
  'wonder',
  {
    attributesToHighlight: ['*'],
  }
)
```

### Custom Search With Filters
```js
await index.updateAttributesForFaceting([
    'id',
    'genres'
  ])
await index.search(
  'wonder',
  {
    filters: 'id > 1 AND genres=Action'
  }
)
```

**Comment by curquiza** [comment] 2021-10-07 12:11
Hum the issue is the `updateAttributesForFaceting` is asynchronous so your example will not work
Maybe in two parts?
It also introduce the settings notion :)

------

### Custom Search With Filters

If you want to enable filtering, you must add your attributes to the `filterableAttributes` index setting.

```js
await index.updateAttributesForFaceting([
    'id',
    'genres'
  ])
```

You only need to perform this operation once.

Note that MeiliSearch will rebuild your index whenever you update `filterableAttributes`. Depending on the size of your dataset, this might take time.


Then, you can perform the search:

```js
await index.search(
  'wonder',
  {
    filters: 'id > 1 AND genres=Action'
  }
)

```

**Comment by brunoocasali** [comment] 2023-02-27 17:53
I'm closing this issue since all the issues were created in the following repositories, and the most important ones were finished as well! Thanks team 🎉

**Closed by brunoocasali** 2023-02-27 17:53 UTC
Labels: ready to implement, SDKs, issues available in repos
