### ISSUE TITLE
SQL export to MeiliSearch - MVP

### ISSUE THREAD

**Issue by tpayet** [meilisearch/integration-guides#20] opened 2020-05-20 10:58 UTC
We want to offer the ability to export any SQL table to MeiliSearch.
The most used databases offer a SQL interface, so we should be able to read any table and stores  its rows into MeiliSearch.

I started to write a Ruby script that could export rows from an sqlite table, but is it the right tool to do this?

We might not need performance here, but a tool that most people could use without having to install lots of dependencies. 

Some databases such as PostgreSQL offer the ability to write extension, this could be the cleanest way to work with automatic export but this kind of work might tedious if we have to do it with every table.

The MVP could be a Ruby (or any other scripting language) script, that can connect to SQLite, PostgreSQL or MySQL that we could run on Heroku as a scheduled task and that could take any table from any database and make a full export to a given index in MeiliSearch.

I would love to have any input from the team to see if can't make something more simpler than this?

**Comment by eskombro** [comment] 2020-05-23 15:38
We can create a lambda function (for example, AWS) with a script (like your ruby script), receiving as input the SQL database authentication credentials and MeiliSearch authentication credentials, and running an export on demand ourselves?

**Comment by curquiza** [comment] 2020-05-25 08:50
Not exactly the same, but I've already started to write a ruby script to parse a (basic) Postgres SQL dump file and push it into MeiliSearch. Not sure that is the best way. Maybe it's better to connect directly to the DB? What do you think?

> The MVP could be a Ruby (or any other scripting language) script, that can connect to SQLite, PostgreSQL or MySQL that we could run on Heroku as a scheduled task and that could take any table from any database and make a full export to a given index in MeiliSearch.

Maybe I understood wrong, but for me that would be a script provided for the user. Why a Heroku Scheduler?

**Comment by eskombro** [comment] 2020-05-25 08:58
We could use a serverless script (for example Lambda function in AWS) you provide credentials as parameters, and the script request the DB and pushes to MeiliSearch. So no need to install/download anything. We can make a little form with github pages where user provides DB credentials, MeiliSearch credentials, and for example the DB table he wants indexed. What do you think?

**Comment by tpayet** [comment] 2020-05-25 09:16
> Not exactly the same, but I've already started to write a ruby script to parse a (basic) Postgres SQL dump file and push it into MeiliSearch. Not sure that is the best way. Maybe it's better to connect directly to the DB? What do you think?

Exactly, not the same but still useful. The problem is could be that it can only parse PostgreSQL dump, or is it SQL standard? but yes let's go with a script that connect to SQL first!

> Maybe I understood wrong, but for me that would be a script provided for the user. Why a Heroku Scheduler?

Sorry about the Heroku scheduler and stuff, this is clearly not MVP and can be done once we have a working script ^^ Sane for aws lambda etc

## Requirements

- Should connect to any SQL database (MVP for MySQL, SQLite & PostgreSQL)
- Should read one column and exports its rows to MeiliSearch
- If nb rows > 5000(arbitrary number here) documents, we should export by chunk of 5000 documents

Is that all? Do we need more precision?

**Comment by eskombro** [comment] 2020-05-25 09:29
> Should read one column and exports its rows to MeiliSearch

One table?

**Comment by eskombro** [comment] 2020-05-25 10:46
SQLAlchemy is a python lib that can handle `SQLite, Postgresql, MySQL, Oracle, MS-SQL, Firebird, Sybase and others`

**Comment by curquiza** [comment] 2020-05-25 11:47
@tpayet could you please write a basic getting started so that we can understand the real expected behavior and maybe anticipate issues? 🙂

**Comment by tpayet** [comment] 2020-05-25 14:34
# README Drive development

## Usage

This readme is designed with Python in mind, the readme should be the same with Ruby or any other scripting language

### Installation
```bash
$ pipenv install meili2sql
```

### Configuration
`meili2sql.yaml` or equivalent in `json` or `INI` file
```yaml
---
database:
  adapter: postgresql # or sqlite or mysql
  host: localhost
  port: 5432
  username: tpayet
  password: blahblahblah
  database: default
  table: Movies

meilisearch:
  host: localhost
  api-key: megamasterkeytopsecure
  index: movies #default to same name as table
```
### Run export
```bash
$ python3 sql2meili.py --config meili2sql.yaml
[python-logger] Connecting to SQL database..
[python-logger] Connected to <postgresql://username:*****@host:port/default>
[python-logger] 7654 rows to export to Meili
[python-logger] 5000 rows exported
[python-logger] 2654 rows exported
[python-logger] Export done.  You can search through your data at http://<meilisearch-host>
```

**Comment by bidoubiwa** [comment] 2020-05-25 15:16
Maybe `sql2meili`?

**Comment by curquiza** [comment] 2020-05-25 15:45
Waiting for the approval of @eskombro and @bidoubiwa (remember: 🚀) and I put it as `ready to implement` 😉

**Comment by Kamefrede** [comment] 2020-10-20 17:44
Hey! 
At my day job we are going to start using Meilisearch and I really wanted a way to export SQL tables to MeiliSearch, so I ended up making my own version of sql2meili (https://github.com/kamefrede/sql2meili , still have some revisions to do)
Should I make a pull request somewhere with it?

**Comment by eskombro** [comment] 2020-10-21 18:55
Hey @Kamefrede !

Thanks a lot for this :tada:

I'll try to check it out as soon as possible! We haven't worked on this sql2meili until now, but I am happy to see that you are working on it and up for contributing! I'll talk about it with the integration team, and come back to you! But thanks!

**Comment by curquiza** [comment] 2020-10-22 15:00
Hello @Kamefrede!
We discussed it with the team (@eskombro was there too 😉). To be honest, we did not take the time to start this issue so far, but be sure we are going to have a look at your work when starting.
Because we might want to test it in the future, could you add a README so that we can use it or communicate about what you've done? 🙂
Thanks for this kind of project you built, it contributes to helping the MeiliSearch community!

**Comment by Kamefrede** [comment] 2020-10-23 09:44
I have added a README that should explain pretty well how it works and the basic usage! (I think so, at least)

If you do end up having any questions about it, don't hesitate to mention me! I'm glad to help :)

**Comment by curquiza** [comment] 2020-10-23 09:57
Thanks for adding the README it looks really detailed! 😁
It's really nice to you! Sure we will contact you if needed 🙂

I don’t know if you are already on [our Slack](https://slack.meilisearch.com/), feel free to joins us, it might be easier to discuss (I’m Clementine).

**Comment by eskombro** [comment] 2020-10-26 17:56
Thanks @Kamefrede 🎉

**Comment by rrjanbiah** [comment] 2020-11-11 15:56
FWIW... instead of one-time export, it would be better to provide integration guide for the CDC approaches using Debezium and Kafka.. especially for the Postgres. Reason: One-time export is only an MVP and not a real world usecase.

**Comment by rrjanbiah** [comment] 2020-11-13 07:40
> FWIW... instead of one-time export, it would be better to provide integration guide for the CDC approaches using Debezium and Kafka.. especially for the Postgres. Reason: One-time export is only an MVP and not a real world usecase.

FWIW, again.. Looks like https://github.com/supabase/realtime by @kiwicopple is an interesting candidate here

**Comment by rrjanbiah** [comment] 2023-03-18 04:17
@long2ice Really interesting. Thanks for sharing. You may add note about performance and especially how it can be comparable with Kafka. Thanks again

**Comment by bidoubiwa** [comment] 2023-03-20 11:30
Hey @long2ice thanks a lot for this tool :) It's amazing 🔥

From my understanding, your tool provides the possibility to dump your SQL content into Meilisearch.
Just to be sure:

1. 
Does it handle relationships? It may be adding too much complexity for little value.

2.
> Which is a python class with pre_event and post_event methods, the pre_event method is called before insert to MeiliSearch, the post_event method is called after insert to MeiliSearch.

Is there also a plugin that listens to SQL operations? For example, if I add an entry in a table, would that entry also be added in Meilisearch?

3.
When refreshing you delete all the data of an index.
```py
await meili.delete_all_data(sync.index_name)
```

To avoid downtime, it is better to use the [`swap` API](https://docs.meilisearch.com/reference/api/indexes.html#delete-an-index).

**Comment by bidoubiwa** [comment] 2023-03-21 15:18
Hey @long2ice, 

I dug more into your tool, and it is incredible. We definitely want to use it internally and are very hyped about it :fire:

I was wondering, what are you expecting for us to help you? 
Do you want us to help you maintain the code? Help you stay aware of the new features added in Meilisearch that might impact/improve your tool? Communicate in some way about it to raise awareness?

If we do use it internally, the only thing we would probably want is some write permissions on the repository to ensure the project stays active.

**Comment by brunoocasali** [comment] 2023-04-24 11:47
Amazing @long2ice 🎉 

I think we can start with @brunoocasali, @bidoubiwa, and @alallema. That is our entire integration team 😬

**Comment by dohankk** [comment] 2023-07-19 03:29
[long2ice](https://github.com/long2ice)

Does meilisync sync updates as well?

**Comment by dohankk** [comment] 2023-07-19 04:05
[long2ice](https://github.com/long2ice)
great !!

**Comment by brunoocasali** [comment] 2023-08-02 04:12
Hello, everyone watching this issue!

Working on a project like this was in our plans for a long time, but we didn't find the right time to do it. 
Thankfully @long2ice did a fantastic job in the [meilisync](https://github.com/long2ice/meilisync), and the Meilisearch team has been using it internally and contributing to it whenever possible.

So I'll close this issue in favor of [meilisync](https://github.com/long2ice/meilisync).

**Closed by brunoocasali** 2023-08-02 04:12 UTC
Labels: ready to implement
